CREATE TABLE `wp_modules` (
  `ID` bigint(20) UNSIGNED NOT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description_text` longtext COLLATE utf8mb4_unicode_ci,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `number_of_linked_courses` int(11) DEFAULT NULL,
  `library_id` bigint(11) UNSIGNED DEFAULT NULL,
  `category_id` int(11) DEFAULT NULL,
  `org_id` bigint(20) UNSIGNED NOT NULL,
  `user_id` bigint(20) UNSIGNED DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `wp_modules` (`ID`, `title`, `description_text`, `created_at`, `updated_at`, `number_of_linked_courses`, `library_id`, `category_id`, `org_id`, `user_id`) VALUES
(2, '15 Passenger Van Safety', '', NULL, NULL, 3, 1, 1, 0, NULL),
(5, 'Achieving Supervisory Balance', '', NULL, NULL, 3, 1, 2, 0, NULL),
(9, 'Active Lifeguarding', '', NULL, NULL, 13, 1, 1, 0, NULL),
(15, 'Advanced Skills for Working with Difficult Parents, Part I', '', NULL, NULL, 16, 1, 3, 0, NULL),
(19, 'Advanced Skills for Working with Difficult Parents, Part II', '', NULL, NULL, 15, 1, 3, 0, NULL),
(24, 'Advanced Staff Supervision, Part I', '', NULL, NULL, 13, 1, 2, 0, NULL),
(29, 'Advanced Staff Supervision, Part II', '', NULL, NULL, 12, 1, 2, 0, NULL),
(35, 'Afterschool Program Success, Part I', '', NULL, NULL, 11, 1, 4, 0, NULL),
(39, 'Afterschool Program Success, Part II', '', NULL, NULL, 11, 1, 4, 0, NULL),
(43, 'Alcohol Beverage Laws', '', NULL, NULL, 14, 1, 1, 0, NULL),
(53, 'Anaphylactic Emergencies', '', NULL, NULL, 24, 1, 1, 0, NULL),
(59, 'Attention Deficit Hyperactivity Disorder', '', NULL, NULL, 14, 1, 5, 0, NULL),
(63, 'Autism Spectrum Disorder', '', NULL, NULL, 9, 1, 5, 0, NULL),
(66, 'Awesome Archery, Part I', '', NULL, NULL, 2, 1, 4, 0, NULL),
(68, 'Awesome Archery, Part II', '', NULL, NULL, 2, 1, 4, 0, NULL),
(71, 'Becoming a Youth Development Professional, Part I', '', NULL, NULL, 14, 1, 4, 0, NULL),
(75, 'Becoming a Youth Development Professional, Part II', '', NULL, NULL, 3, 1, 4, 0, NULL),
(79, 'Behavior-Based Interviewing', '', NULL, NULL, 9, 1, 2, 0, NULL),
(83, 'Best Boys, Part I', '', NULL, NULL, 14, 1, 3, 0, NULL),
(87, 'Best Boys, Part II', '', NULL, NULL, 8, 1, 3, 0, NULL),
(91, 'Boov Ship Game', '', NULL, NULL, 3, 1, 7, 0, NULL),
(93, 'Bullies and Targets, Part I', '', NULL, NULL, 14, 1, 5, 0, NULL),
(97, 'Bullies and Targets, Part II', '', NULL, NULL, 14, 1, 5, 0, NULL),
(101, 'Burn Specific Programming, Part I', '', NULL, NULL, 8, 1, 4, 0, NULL),
(105, 'Burn Specific Programming, Part II', '', NULL, NULL, 8, 1, 4, 0, NULL),
(109, 'Canoeing Success, Part I', '', NULL, NULL, 8, 1, 4, 0, NULL),
(113, 'Canoeing Success, Part II', '', NULL, NULL, 9, 1, 4, 0, NULL),
(117, 'Child Welfare and Protection', '', NULL, NULL, 16, 1, 3, 0, NULL),
(121, 'Children with Verbal Learning Disabilities', '', NULL, NULL, 9, 1, 5, 0, NULL),
(125, 'Christian Perspectives, Part I', '', NULL, NULL, 3, 1, 3, 0, NULL),
(129, 'Christian Perspectives, Part II', '', NULL, NULL, 3, 1, 3, 0, NULL),
(133, 'Classic Problem Solving', '', NULL, NULL, 9, 1, 3, 0, NULL),
(137, 'Confidentiality for Youth Professionals', '', NULL, NULL, 6, 1, 1, 0, NULL),
(142, 'Cracking Kids’ Secret Code', '', NULL, NULL, 10, 1, 3, 0, NULL),
(147, 'Cultivating Patience', '', NULL, NULL, 8, 1, 4, 0, NULL),
(152, 'Cultural Competence in Youth Programs, Part I', '', NULL, NULL, 7, 1, 0, 0, NULL),
(157, 'Cultural Competence in Youth Programs, Part II', '', NULL, NULL, 4, 1, 3, 0, NULL),
(163, 'Cyberbullying and Sexting', '', NULL, NULL, 5, 1, 1, 0, NULL),
(165, 'Day Camp Dynamics, Part I', '', NULL, NULL, 6, 1, 3, 0, NULL),
(169, 'Day Camp Dynamics, Part II', '', NULL, NULL, 6, 1, 3, 0, NULL),
(173, 'Day Camp Dynamics, Part III', '', NULL, NULL, 7, 1, 3, 0, NULL),
(176, 'Dealing with Difficult Parents, Part I - scorm', 'Sometimes its hard to deal with parents.\n', NULL, NULL, 6, 1, 3, 0, NULL),
(179, 'Difficult Management Conversations, Part I', '', NULL, NULL, 9, 1, 2, 0, NULL),
(183, 'Difficult Management Conversations, Part II', '', NULL, NULL, 4, 1, 2, 0, NULL),
(187, 'Dot Painting', '', NULL, NULL, 2, 1, 7, 0, NULL),
(189, 'Duty of Care, Part I', '', NULL, NULL, 9, 1, 1, 0, NULL),
(194, 'Duty of Care, Part II', '', NULL, NULL, 9, 1, 1, 0, NULL),
(200, 'Effective Debriefing Tools and Techniques', '', NULL, NULL, 5, 1, 0, 0, NULL),
(204, 'Equity & Diversity', '', NULL, NULL, 7, 1, 0, 0, NULL),
(206, 'Equity and Diversity', '', NULL, NULL, 9, 1, 4, 0, NULL),
(210, 'Face-to-Face (Differently Abled Youth)', '', NULL, NULL, 4, 1, 4, 0, NULL),
(214, 'Fairytale Hats', '', NULL, NULL, 2, 1, 7, 0, NULL),
(217, 'Fire Building and Fire Safety', '', NULL, NULL, 6, 1, 0, 0, NULL),
(222, 'Fire Evacuation Planning', '', NULL, NULL, 6, 1, 1, 0, NULL),
(226, 'Firing a Staff Member', '', NULL, NULL, 4, 1, 2, 0, NULL),
(230, 'Get the Best and Forget the Rest', '', NULL, NULL, 3, 1, 3, 0, NULL),
(234, 'Girl Power', '', NULL, NULL, 5, 1, 3, 0, NULL),
(239, 'Good Sportsmanship vs. Foul Play', '', NULL, NULL, 9, 1, 5, 0, NULL),
(244, 'Hello Games', '', NULL, NULL, 6, 1, 4, 0, NULL),
(248, 'Helping Awkward Children Fit In', '', NULL, NULL, 4, 1, 5, 0, NULL),
(255, 'Homesickness at Day & Resident Camps, Part I', '', NULL, NULL, 12, 1, 5, 0, NULL),
(261, 'Homesickness at Day & Resident Camps, Part II', '', NULL, NULL, 11, 1, 5, 0, NULL),
(265, 'How to Create Staff Groups', '', NULL, NULL, 5, 1, 0, 0, NULL),
(266, 'How to Enroll Staff into Courses', '', NULL, NULL, 5, 1, 0, 0, NULL),
(267, 'How to Invite/Create Staff Users', '', NULL, NULL, 5, 1, 0, 0, NULL),
(268, 'How to polish poles at Winbaums Camp', '', NULL, NULL, 1, 1, 0, 0, NULL),
(270, 'Jewish Perspectives on Child-Staff Relationships, Part I', '', NULL, NULL, 5, 1, 5, 0, NULL),
(274, 'Jewish Perspectives on Child-Staff Relationships, Part II', '', NULL, NULL, 5, 1, 5, 0, NULL),
(278, 'Jewish Perspectives on Staff Happiness and Stamina', '', NULL, NULL, 4, 1, 4, 0, NULL),
(282, 'Juggling Balls', '', NULL, NULL, 2, 1, 7, 0, NULL),
(284, 'Kachina Dolls', '', NULL, NULL, 2, 1, 7, 0, NULL),
(286, 'Kickin’ Kitchens', '', NULL, NULL, 3, 1, 1, 0, NULL),
(290, 'Leader of the Pack', '', NULL, NULL, 2, 1, 7, 0, NULL),
(292, 'Lifeguarding Skills Verification', '', NULL, NULL, 7, 1, 1, 0, NULL),
(297, 'Listening with More Than Ears', '', NULL, NULL, 3, 1, 5, 0, NULL),
(300, 'Masterful Meetings', '', NULL, NULL, 2, 1, 2, 0, NULL),
(303, 'Medical Preparation for Burn Camps', '', NULL, NULL, 3, 1, 1, 0, NULL),
(307, 'Move It Like You Mean It', '', NULL, NULL, 8, 1, 4, 0, NULL),
(311, 'New Module Title', '', NULL, NULL, 1, 1, 0, 0, NULL),
(314, 'No Losers', '', NULL, NULL, 3, 1, 3, 0, NULL),
(318, 'Out of the Pool and Into the Wild', '', NULL, NULL, 7, 1, 1, 0, NULL),
(324, 'Outdoor Cooking with Youth', '', NULL, NULL, 5, 1, 0, 0, NULL),
(328, 'Personality Synergy', '', NULL, NULL, 2, 1, 3, 0, NULL),
(331, 'Playing with a Full Deck', '', NULL, NULL, 8, 1, 4, 0, NULL),
(338, 'Preventing Gossip and Relational Aggression', '', NULL, NULL, 7, 1, 0, 0, NULL),
(343, 'Programming For All (Differently Abled Youth)', '', NULL, NULL, 6, 1, 0, 0, NULL),
(348, 'Providing Effective Feedback, Part I', '', NULL, NULL, 7, 1, 2, 0, NULL),
(352, 'Providing Effective Feedback, Part II', '', NULL, NULL, 3, 1, 2, 0, NULL),
(357, 'Rainy Day Games', '', NULL, NULL, 4, 1, 4, 0, NULL),
(362, 'Regional Disaster Management for Youth Programs', '', NULL, NULL, 7, 1, 1, 0, NULL),
(367, 'Respect is Learned, Not Given', '', NULL, NULL, 4, 1, 3, 0, NULL),
(372, 'Rules Were Made to Be Positive', '', NULL, NULL, 8, 1, 3, 0, NULL),
(377, 'Safe Touch & Safe Talk', '', NULL, NULL, 22, 1, 1, 0, NULL),
(385, 'Sand Art', '', NULL, NULL, 2, 1, 7, 0, NULL),
(388, 'Sexual Harassment', '', NULL, NULL, 6, 1, 0, 0, NULL),
(392, 'Shockingly Professional Talk, Part I', '', NULL, NULL, 2, 1, 1, 0, NULL),
(394, 'Shockingly Professional Talk, Part II', '', NULL, NULL, 2, 1, 1, 0, NULL),
(398, 'Skillful Discipline, Part I', '', NULL, NULL, 13, 1, 5, 0, NULL),
(405, 'Skillful Discipline, Part II', '', NULL, NULL, 11, 1, 5, 0, NULL),
(410, 'Speaking of Camp', '', NULL, NULL, 11, 1, 4, 0, NULL),
(416, 'Staff Use of the Internet', '', NULL, NULL, 7, 1, 0, 0, NULL),
(420, 'Stop Yelling Get the HINT', '', NULL, NULL, 14, 1, 3, 0, NULL),
(427, 'Supervising Junior Leaders', '', NULL, NULL, 8, 1, 2, 0, NULL),
(433, 'Swim Checks in Action', '', NULL, NULL, 7, 1, 1, 0, NULL),
(438, 'Totem Pole', '', NULL, NULL, 2, 1, 7, 0, NULL),
(440, 'Waterfront Safety Design', '', NULL, NULL, 7, 1, 1, 0, NULL),
(447, 'We Squashed It! - Physical Aggression', '', NULL, NULL, 6, 1, 3, 0, NULL),
(451, 'We Squashed it! - Relational Aggression', '', NULL, NULL, 12, 1, 3, 0, NULL),
(455, 'Weather Watch', '', NULL, NULL, 9, 1, 1, 0, NULL),
(460, 'Wilderness Wellness', '', NULL, NULL, 6, 1, 1, 0, NULL),
(464, 'Winning Ways of Skilled Supervisors', '', NULL, NULL, 8, 1, 2, 0, NULL),
(469, 'Wise Use of Time Off', '', NULL, NULL, 9, 1, 1, 0, NULL),
(475, 'Youth Inspired', '', NULL, NULL, 13, 1, 4, 0, NULL),
(483, 'Test Module 1', 'test', '2017-05-31 00:00:00', NULL, NULL, 0, 0, 692, 88),
(484, 'Back to camp basics for boys', 'test', '2017-05-31 00:00:00', NULL, NULL, 0, 0, 692, 88);




