INSERT INTO `wp_modules` (`ID`, `title`, `description_text`, `created_at`, `updated_at`, `number_of_linked_courses`, `library_id`, `category_id`, `org_id`, `creator_id`, `video_id`) 
VALUES 
(null, 'Gender and Sexuality in Youth Programs: Aligning Respect, Kindness, and Inclusiveness', 'The male-female distinction used to be a social staple. Assigned at birth, gender was a constant—if sometimes misguided—hallmark of identity. Today, we are beginning to understand the complex biopsychosocial interactions between chromosomal sex and gender identity. This sensitively co-hosted module will equip all youth-serving organizations to welcome their first transgender participants.', '2017-09-26 00:00:00', NULL, NULL, '1', '3', '0', NULL, 180),
(null, 'Cross-Cultural Agility: How to Shed Your Earth Suit', '“Diversity is who you invite to the party; inclusion is who you ask to dance; but cross-cultural agility is when groups share their native dances with each other.” So says Niambi. This provocative video is an in-your-face dare to elevate superficial diversity and inclusion to the virtuous plane of cross-cultural agility. Vulnerability and sharing are the keys to this peaceful, multicultural kingdom.', '2017-09-26 00:00:00', NULL, NULL, '1', '3', '0', NULL, 178),
(null, 'Leading with Control and Warmth: The Authoritative Balance of Power', 'Drawing on Baumrind’s landmark research, this foundational module brings the four-quadrant model of leadership and parenting to life. Witness the harmful effects of [high control + low warmth] or [low control + low warmth] or [low control + high warmth]. The balanced approach of [high control + high warmth]—called authoritative—yields happy, compliant, and high-achieving youth.', '2017-09-26 00:00:00', NULL, NULL, '1', '3', '0', NULL, 177),
(null, 'Woodworking with Hand Tools, Part 1: Setting Up Shop', 'The elegance of traditional woodworking is matched only by its beauty. But the creative process is what pulls young people in and keeps then engaged, right from the start. In Part 1 of this innovative three-part series, you’ll learn why woodworking with hand tools is superior to power tools in youth programs, how to make a sturdy workbench, install beefy vices, and set-up proper lighting.', '2017-09-26 00:00:00', NULL, NULL, '1', '4', '0', NULL, 169),
(null, 'Woodworking with Hand Tools, Part 2: Tools and Supplies', 'In Part 2 of this three-part series, Chris explains details of the 15 hand-tools and 5 supplies every traditional woodworker needs. From pencils to block planes and hammers to beeswax, you’ll learn surprising facts about the 20 ingredients you’ll need to make every project in the EOT library, plus hundreds more. See how manual tools harness wood’s beauty when handled skillfully.', '2017-09-26 00:00:00', NULL, NULL, '1', '4', '0', NULL, 170),
(null, 'Woodworking with Hand Tools, Part 3: Safety and Hacks', 'Protecting your eyes, lungs, and hands is the foundation of shop safety. Unfortunately, most woodworkers neglect the protections and procedures that prolong life and limb. In Part 3 of this three-part series, take a detailed look at safety glasses, sniff around for good dusk masks, and slice through the myths about cut gloves. Bonus footage includes Chris’s Top-Ten shop hacks!', '2017-09-26 00:00:00', NULL, NULL, '1', '4', '0', NULL, 171),
(null, 'Woodworking Projects by Hand: Cutting Boards and Curio Shelves', 'Vivid, step-by-step instructions for two woodshop favorites: cutting boards and curio shelves. Using reclaimed walnut, Chris demonstrates the use of a measuring tape, speed square, block plane, and various grits of sandpaper to create a lustrous cutting board with a food-safe finish. Then, see how careful cutting and creative fastening produce a curio shelf for displaying memorabilia.', '2017-09-26 00:00:00', NULL, NULL, '1', '4', '0', NULL, 172),
(null, 'Woodworking Projects by Hand: Coat Hook Racks and Picture Frames', 'Sticks lying on the forest floor become the rustic centerpiece of a functional and stylish set of coat hooks. Plus, learn what makes a high-quality auger bit and see why lining your vices with hardwood saves time. Then, create an heirloom-quality picture frame from clear New Zealand pine, using a miter box to cut accurate 45s and dowel pins to line-up hand-drilled holes for fastening corners.', '2017-09-26 00:00:00', NULL, NULL, '1', '4', '0', NULL, 173),
(null, 'Woodworking Projects by Hand: Boxes and Ping Pong Paddles', 'Cubic meets curvy in this fun combination of practical projects. You’ll learn three different ways to construct a pint-sized box with a whisper-quiet leather hinge. Then get ready to play, because Chris demonstrates how to get coping saws and woodworking vices to cooperate in the creation of a customized table tennis paddle made of ¼” plywood, 100-grit sandpaper, and a reclaimed ash bough. ', '2017-09-26 00:00:00', NULL, NULL, '1', '4', '0', NULL, 174),
(null, 'Suicidality in Youth Programs, Part 1: Assessment and Support Basics', 'Lay assessment of suicidality requires patience, empathy, a clear explanation of confidentiality, and a timely referral to a qualified professional. Although rare in youth, suicidal thoughts, feelings, and behaviors are urgent matters for which all leaders need to be ready. Part 1 of this module features a guided, step-by-step case example of a conversation with a suicidal youngster.', '2017-09-26 00:00:00', NULL, NULL, '1', '5', '0', NULL, 175),
(null, 'Suicidality in Youth Programs, Part 2: Sidestepping Support Pitfalls', 'Talking about suicide makes most youth leaders uncomfortable. But avoiding the topic will leave you unprepared. To better equip you to provide support to a suicidal child or teen, Part 2 of module demonstrates honest solutions to common pitfalls of lay assessment: avoiding the subject of suicide; minimizing expressions of distress; and overstating the parameters of confidentiality. ', '2017-09-26 00:00:00', NULL, NULL, '1', '5', '0', NULL, 176),
(null, 'Customer Service Excellence: Details, Language, and Solutions', 'Bad days get worse fast when customer service stinks. We’ve all experienced terrible customer service in airports, in restaurants, and over the phone with so-called “specialists.” So, instead of listening carefully because the menu has changed, climb aboard with Harley-riding Marine, Kurt Podeszwa, to learn all the industry best-practices for providing exceptional customer service.\r\n', '2017-09-26 00:00:00', NULL, NULL, '1', '2', '0', NULL, 181),
(null, 'Promoted to Supervisor! Leadership Skills for Newly-Minted Managers', 'Congratulations! Few industries promote from the front lines to the supervisory ranks without explicit training. Your exemplary youth leadership has vaulted you to a higher paygrade but an unfamiliar skill set. This practical video for internally promoted staff shows you what to embrace, what to avoid, and how to draw the best from those you are supervising—without alienating them as friends.', '2017-09-26 00:00:00', NULL, NULL, '1', '2', '0', NULL, 179),
(null, 'Canoeing Success, Part III: Capsizing and Safe Rescue', 'It’s all part of the sport, but tipping over in a canoe can be stressful…if you’ve never done it before. Away from calm water or a familiar shoreline, you’ll be glad you can perform a competent rescue. Part III of this beautifully filmed series teaches the proper way to rescue a canoe that has overturned, drain and right it with stability, and re-enter the craft with grace and newfound confidence. A safety essential.', '2017-09-26 00:00:00', NULL, NULL, '1', '4', '0', NULL, 182);
/* Update the category ID which causing some of the modules to not show in view library page.... */
UPDATE `wp_modules`
SET category_id = 3
WHERE `title` = 'Cultural Competence in Youth Programs, Part I';
UPDATE `wp_modules`
SET category_id = 4
WHERE `title` in ('Effective Debriefing Tools and Techniques', 'Outdoor Cooking with Youth', 'Programming For All (Differently Abled Youth)');
UPDATE `wp_modules`
SET category_id = 5
WHERE `title` in ('Child Welfare and Protection', 'Fire Building and Fire Safety', 'Sexual Harassment');
UPDATE `wp_modules`
SET category_id = 2
WHERE `title` in ('Personality Synergy', 'Fire Building and Fire Safety', 'Sexual Harassment');